-- โครงฐานข้อมูลฝั่ง PostgreSQL — source of truth เดียวของโครงสร้าง
--
-- ต่างจาก schema.sql เดิม (SQLite) ตรงที่ไม่มีประวัติการย้ายรุ่นปนอยู่:
-- ฐานข้อมูล Postgres เริ่มจากศูนย์แล้วนำเข้าข้อมูลจาก SQLite ครั้งเดียว
-- จึงไม่ต้องมีขั้นอัปเกรดของรุ่นเก่าให้แบกต่อ
--
-- กติกาที่ตั้งใจรักษาไว้ให้เหมือน SQLite เป๊ะ ๆ เพื่อไม่ให้โค้ดแอปต้องเปลี่ยนตาม:
--   · คอลัมน์จริง/เท็จ เก็บเป็น INTEGER 0/1 ไม่ใช่ BOOLEAN — โค้ดเทียบ === 1 อยู่หลายร้อยที่
--   · เวลา เก็บเป็นข้อความ 'YYYY-MM-DD HH:MI:SS' เวลา UTC เหมือนที่ datetime('now')
--     ของ SQLite คืนมา — format.ts เติม "Z" ต่อท้ายแล้วแปลงเป็นเวลาไทยตอนแสดง
--   · id เป็น INTEGER (ไม่ใช่ BIGINT) เพราะโค้ดส่งต่อเป็น number ของ JS

-- แทน datetime('now') ของ SQLite — คืนข้อความเวลา UTC รูปแบบเดียวกัน
CREATE OR REPLACE FUNCTION utc_now_text() RETURNS text
  LANGUAGE sql STABLE AS
$$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;

-- แทน date('now') ของ SQLite — วันที่ตามเวลา UTC
CREATE OR REPLACE FUNCTION utc_today_text() RETURNS text
  LANGUAGE sql STABLE AS
$$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD') $$;

-- แทน datetime('now', '-15 minutes') — ตัวปรับเวลาของ SQLite เขียนเหมือน interval ของ Postgres
CREATE OR REPLACE FUNCTION utc_now_text(shift text) RETURNS text
  LANGUAGE sql STABLE AS
$$ SELECT to_char((now() AT TIME ZONE 'UTC') + shift::interval, 'YYYY-MM-DD HH24:MI:SS') $$;

-- แทน date('now','localtime') — วันที่ตามเวลาไทย ใช้ตัดสินว่า "วันนี้" คือวันไหนสำหรับคนใช้งาน
CREATE OR REPLACE FUNCTION local_today() RETURNS date
  LANGUAGE sql STABLE AS
$$ SELECT (now() AT TIME ZONE 'Asia/Bangkok')::date $$;

/*
 * ฟังก์ชันอ่านวันเวลาจากข้อความ
 *
 * ระบบเก็บวันเวลาเป็นข้อความหลายรูป: 'YYYY-MM-DD HH:MI:SS' (จากฐานข้อมูล),
 * 'YYYY-MM-DDTHH:MI:SS.sssZ' (จาก JS) และ 'YYYY-MM-DD' (ช่องวันที่ในฟอร์ม)
 * รวมถึงข้อความว่างในคอลัมน์ที่ NOT NULL DEFAULT ''
 *
 * SQLite ปล่อยให้ค่าที่อ่านไม่ออกกลายเป็น NULL เงียบ ๆ — Postgres จะโยน error
 * และทำให้ทั้งคำสั่งล้ม จึงต้องดักไว้ให้ได้พฤติกรรมเดิม ไม่งั้นข้อมูลเก่าแถวเดียว
 * ที่ค่าเพี้ยนจะทำให้หน้าสถิติทั้งหน้าพัง
 */
CREATE OR REPLACE FUNCTION sql_ts(v text) RETURNS timestamp
  LANGUAGE plpgsql IMMUTABLE AS $fn$
BEGIN
  IF v IS NULL OR btrim(v) = '' THEN RETURN NULL; END IF;
  RETURN v::timestamp;
EXCEPTION WHEN others THEN RETURN NULL;
END $fn$;

-- แทน date(x) ของ SQLite — ตัดเวลาออกเหลือแต่วันที่
CREATE OR REPLACE FUNCTION sql_date(v text) RETURNS date
  LANGUAGE plpgsql IMMUTABLE AS $fn$
BEGIN
  IF v IS NULL OR btrim(v) = '' THEN RETURN NULL; END IF;
  RETURN substring(btrim(v) from 1 for 10)::date;
EXCEPTION WHEN others THEN RETURN NULL;
END $fn$;

/*
 * แทน julianday(x) — จำนวนวันแบบทศนิยม
 *
 * โค้ดใช้มันในรูป (julianday(a) - julianday(b)) * 24 เพื่อหาจำนวนชั่วโมง
 * ฟังก์ชันนี้จึงต้องคืนค่าที่ "ผลต่างคูณ 24 ได้ชั่วโมง" ไม่ต้องตรงกับเลข Julian จริง
 */
CREATE OR REPLACE FUNCTION julian(v text) RETURNS double precision
  LANGUAGE sql IMMUTABLE AS
$$ SELECT EXTRACT(EPOCH FROM sql_ts(v)) / 86400.0 $$;

CREATE OR REPLACE FUNCTION julian_now() RETURNS double precision
  LANGUAGE sql STABLE AS
$$ SELECT EXTRACT(EPOCH FROM now()) / 86400.0 $$;

/*
 * แทน CAST(json_extract(data, '$.key') AS INTEGER) ของ SQLite
 *
 * ใช้หาว่าเอกสารใบไหนอ้างถึงใบไหน (ช่องชนิด REQUEST เก็บ id ไว้ใน JSON)
 * SQLite แปลงค่าที่ไม่ใช่ตัวเลขให้เป็น 0 เงียบ ๆ — ที่นี่คืน NULL ซึ่งตรงกว่า
 * เพราะ 0 ไม่มีทางตรงกับ id จริงอยู่แล้ว ผลลัพธ์ของเงื่อนไขจึงเหมือนเดิม
 */
CREATE OR REPLACE FUNCTION json_int(doc text, key text) RETURNS integer
  LANGUAGE plpgsql IMMUTABLE AS $fn$
DECLARE v text;
BEGIN
  v := doc::jsonb ->> key;
  IF v ~ '^-?[0-9]+$' THEN RETURN v::integer; END IF;
  RETURN NULL;
EXCEPTION WHEN others THEN RETURN NULL;
END $fn$;

CREATE TABLE IF NOT EXISTS departments (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT    NOT NULL UNIQUE,
  active     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL DEFAULT utc_now_text()
);

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT    NOT NULL UNIQUE,
  password      TEXT    NOT NULL,
  name          TEXT    NOT NULL,            -- ชื่อ-นามสกุล (ใช้ในช่องลายเซ็น)
  position      TEXT    NOT NULL DEFAULT '', -- ตำแหน่งที่แสดงใต้ลายเซ็น (ข้อความอิสระ)
  department_id INTEGER REFERENCES departments(id),
  -- หัวหน้าโดยตรง — หัวหน้าเห็นเอกสารของลูกน้องทั้งสายโดยไม่ต้องมีใครแท็กให้
  manager_id    INTEGER REFERENCES users(id),
  -- ผู้ตรวจสอบ: เห็นเอกสารได้ทุกใบเพื่อตรวจย้อนหลัง แต่ไม่ได้สิทธิ์อนุมัติหรือแก้อะไรเพิ่ม
  can_audit     INTEGER NOT NULL DEFAULT 0,
  job_role      TEXT    NOT NULL DEFAULT 'NONE', -- ตำแหน่งงานสำหรับผูกสายอนุมัติ
  lark_user_id  TEXT    NOT NULL DEFAULT '',     -- open_id ใน Lark/Feishu
  sso_sub       TEXT    NOT NULL DEFAULT '',     -- subject จากระบบกลาง (ตัวระบุถาวร)
  sso_roles     TEXT    NOT NULL DEFAULT '',     -- roles/groups ที่ระบบกลางส่งมาล่าสุด (JSON)
  sso_synced_at TEXT,                            -- เข้าระบบผ่าน SSO ครั้งล่าสุดเมื่อไหร่
  locale        TEXT    NOT NULL DEFAULT '',     -- ภาษาที่ผู้ใช้เลือกล่าสุด
  role          TEXT    NOT NULL DEFAULT 'USER'  -- MANAGER = หัวหน้าทีม เห็นเอกสารทั้งแผนกของตน
                CHECK (role IN ('ADMIN','MANAGER','USER')),
  active        INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT    NOT NULL DEFAULT utc_now_text(),
  signature     TEXT    NOT NULL DEFAULT '',  -- ชื่อไฟล์รูปลายเซ็นในโฟลเดอร์อัปโหลด
  avatar_url    TEXT    NOT NULL DEFAULT '',  -- รูปโปรไฟล์จากระบบกลาง (ว่าง = ใช้วงกลมตัวอักษร)
  must_change_password INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_users_dept ON users(department_id);

CREATE TABLE IF NOT EXISTS form_categories (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT    NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  active     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS form_templates (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         TEXT    NOT NULL UNIQUE,      -- ใช้ในเลขที่เอกสาร เช่น DISCOUNT
  name         TEXT    NOT NULL,
  category_id  INTEGER REFERENCES form_categories(id),
  icon         TEXT    NOT NULL DEFAULT '📄',
  color        TEXT    NOT NULL DEFAULT '',  -- สีไอคอนบนการ์ด (ดู TEMPLATE_COLORS)
  description  TEXT    NOT NULL DEFAULT '',
  active       INTEGER NOT NULL DEFAULT 1,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  record_submitter INTEGER NOT NULL DEFAULT 1,  -- บันทึกชื่อผู้กรอกฟอร์มไหม
  -- ตัวย่อที่โผล่ในเลขที่เอกสาร เช่น MKT → AP-MKT-202608-0007
  -- ว่าง = ให้ระบบย่อจาก code ให้เอง (ดู docPrefixOf ใน queries.ts)
  doc_prefix   TEXT    NOT NULL DEFAULT '',
  -- ต้องเคลียร์ค่าใช้จ่ายใน OA ภายในกี่วันหลังอนุมัติ · 0 = ไม่ต้องติดตาม
  clear_within_days INTEGER NOT NULL DEFAULT 0,
  -- ต้องยื่นล่วงหน้ากี่วัน · 0 = ไม่บังคับ
  lead_days        INTEGER NOT NULL DEFAULT 0,
  lead_urgent_days INTEGER NOT NULL DEFAULT 0,
  lead_mode        TEXT    NOT NULL DEFAULT 'WARN' CHECK (lead_mode IN ('WARN','BLOCK')),
  print_config TEXT    NOT NULL DEFAULT '{}',  -- ตั้งค่าการพิมพ์ (ดู src/lib/print.ts)
  signature_mode TEXT  NOT NULL DEFAULT 'OPTIONAL'
                 CHECK (signature_mode IN ('NONE','OPTIONAL','REQUIRED')),
  created_at   TEXT    NOT NULL DEFAULT utc_now_text(),
  updated_at   TEXT    NOT NULL DEFAULT utc_now_text()
);

CREATE TABLE IF NOT EXISTS form_fields (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id INTEGER NOT NULL REFERENCES form_templates(id) ON DELETE CASCADE,
  field_key   TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  type        TEXT    NOT NULL DEFAULT 'TEXT',
  field_role  TEXT    NOT NULL DEFAULT '',
  required    INTEGER NOT NULL DEFAULT 0,
  help        TEXT    NOT NULL DEFAULT '',
  options     TEXT    NOT NULL DEFAULT '[]', -- JSON array ของตัวเลือก (SELECT/MULTISELECT)
  -- แสดงช่องนี้เมื่อช่องอื่นถูกเลือกเป็นค่าที่กำหนด ('' = แสดงเสมอ)
  show_if_key   TEXT  NOT NULL DEFAULT '',
  show_if_value TEXT  NOT NULL DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  active      INTEGER NOT NULL DEFAULT 1,
  placeholder TEXT    NOT NULL DEFAULT '',
  sum_of      TEXT    NOT NULL DEFAULT '',
  UNIQUE (template_id, field_key)
);
CREATE INDEX IF NOT EXISTS idx_fields_tpl ON form_fields(template_id, sort_order);

CREATE TABLE IF NOT EXISTS form_table_columns (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id   INTEGER NOT NULL REFERENCES form_fields(id) ON DELETE CASCADE,
  col_key    TEXT    NOT NULL,
  label      TEXT    NOT NULL,
  type       TEXT    NOT NULL DEFAULT 'TEXT', -- TEXT NUMBER MONEY DATE SELECT USER
  required   INTEGER NOT NULL DEFAULT 0,
  options    TEXT    NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0,
  unit       TEXT    NOT NULL DEFAULT '',
  UNIQUE (field_id, col_key)
);

CREATE TABLE IF NOT EXISTS flow_nodes (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id INTEGER NOT NULL REFERENCES form_templates(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL DEFAULT '',
  kind        TEXT    NOT NULL DEFAULT 'APPROVE' CHECK (kind IN ('APPROVE','CC')),
  mode        TEXT    NOT NULL DEFAULT 'SEQUENTIAL' CHECK (mode IN ('SEQUENTIAL','ANY','ALL')),
  stage       TEXT    NOT NULL DEFAULT 'FINAL' CHECK (stage IN ('PRELIM','FINAL')),
  sort_order  INTEGER NOT NULL DEFAULT 1,
  cond_field  TEXT    NOT NULL DEFAULT '',   -- field_key ที่ใช้เป็นเงื่อนไข ('' = ใช้เสมอ)
  cond_op     TEXT    NOT NULL DEFAULT '',   -- GTE LT EQ NEQ
  cond_value  TEXT    NOT NULL DEFAULT '',
  active      INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_nodes_tpl ON flow_nodes(template_id, sort_order);

CREATE TABLE IF NOT EXISTS flow_node_members (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id  INTEGER NOT NULL REFERENCES flow_nodes(id) ON DELETE CASCADE,
  source   TEXT    NOT NULL DEFAULT 'JOB_ROLE' CHECK (source IN ('JOB_ROLE','USER')),
  job_role TEXT    NOT NULL DEFAULT '',
  user_id  INTEGER REFERENCES users(id),
  scope    TEXT    NOT NULL DEFAULT 'ANY' CHECK (scope IN ('ANY','DEPT'))
);

CREATE TABLE IF NOT EXISTS requests (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_no        TEXT    NOT NULL UNIQUE,
  template_id   INTEGER NOT NULL REFERENCES form_templates(id),
  requester_id  INTEGER NOT NULL REFERENCES users(id),
  title         TEXT    NOT NULL DEFAULT '',  -- มาจากฟิลด์ที่ตั้ง role = TITLE
  amount        DOUBLE PRECISION,             -- มาจากฟิลด์ที่ตั้ง role = AMOUNT
  doc_date      TEXT    NOT NULL DEFAULT utc_today_text(),
  data          TEXT    NOT NULL DEFAULT '{}', -- ค่าทุกฟิลด์เก็บเป็น JSON
  status        TEXT    NOT NULL DEFAULT 'DRAFT'
                CHECK (status IN ('DRAFT','PENDING','PRELIM_APPROVED','APPROVED','REJECTED','RETURNED','CANCELLED')),
  stage         TEXT    NOT NULL DEFAULT 'FINAL' CHECK (stage IN ('PRELIM','FINAL')),
  current_step  INTEGER NOT NULL DEFAULT 0,
  -- เหตุผลที่ยื่นไม่ทันกำหนดล่วงหน้า ('' = ยื่นทันปกติ หรือฟอร์มไม่ได้ตั้งกติกา)
  urgent_reason TEXT    NOT NULL DEFAULT '',
  -- ติดตามการเคลียร์ค่าใช้จ่ายใน OA หลังอนุมัติ
  clear_due_date TEXT   NOT NULL DEFAULT '',
  oa_ref         TEXT   NOT NULL DEFAULT '',
  clear_nudged_on TEXT,   -- ทวงเรื่องเคลียร์ OA ครั้งล่าสุดวันไหน (กันทวงซ้ำวันละหลายรอบ)
  cleared_at     TEXT,
  cleared_by     INTEGER REFERENCES users(id),
  submitted_at  TEXT,
  prelim_at     TEXT,
  closed_at     TEXT,
  created_at    TEXT    NOT NULL DEFAULT utc_now_text(),
  updated_at    TEXT    NOT NULL DEFAULT utc_now_text()
);
CREATE INDEX IF NOT EXISTS idx_req_requester ON requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_req_status    ON requests(status);
CREATE INDEX IF NOT EXISTS idx_req_template  ON requests(template_id);

CREATE TABLE IF NOT EXISTS request_approvers (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  stage      TEXT    NOT NULL DEFAULT 'FINAL',
  step_no    INTEGER NOT NULL,
  node_name  TEXT    NOT NULL DEFAULT '',
  kind       TEXT    NOT NULL DEFAULT 'APPROVE',
  mode       TEXT    NOT NULL DEFAULT 'SEQUENTIAL',
  user_id    INTEGER NOT NULL REFERENCES users(id),
  job_role   TEXT    NOT NULL DEFAULT '',
  title      TEXT    NOT NULL DEFAULT '',
  status     TEXT    NOT NULL DEFAULT 'PENDING',
  comment    TEXT    NOT NULL DEFAULT '',
  acted_at   TEXT,
  read_at    TEXT,                          -- สำหรับ CC: เวลาที่เปิดอ่าน
  acted_by   INTEGER REFERENCES users(id),  -- ใครกดจริง (ต่างจาก user_id เมื่ออนุมัติแทน)
  notified_at TEXT,                         -- เวลาที่งานตกถึงมือคนนี้ (ใช้นับว่าค้างกี่วัน)
  last_nudge_at TEXT,                       -- เตือนเรื่องแถวนี้ครั้งล่าสุดเมื่อไหร่
  added_by   INTEGER REFERENCES users(id),  -- ถ้าเป็นผู้อนุมัติที่ถูกแทรกกลางคัน
  from_user  INTEGER REFERENCES users(id)   -- ถ้าถูกถ่ายโอนมา: เจ้าของเดิม
);
CREATE INDEX IF NOT EXISTS idx_appr_req     ON request_approvers(request_id);
CREATE INDEX IF NOT EXISTS idx_appr_user    ON request_approvers(user_id, status);
CREATE INDEX IF NOT EXISTS idx_appr_waiting ON request_approvers(status, kind, notified_at);

CREATE TABLE IF NOT EXISTS request_comments (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id),
  body       TEXT    NOT NULL,
  created_at TEXT    NOT NULL DEFAULT utc_now_text()
);
CREATE INDEX IF NOT EXISTS idx_comments_req ON request_comments(request_id);

CREATE TABLE IF NOT EXISTS attachments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id  INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  field_key   TEXT    NOT NULL DEFAULT '',   -- ไฟล์นี้อยู่ในฟิลด์ไหนของฟอร์ม
  -- ไฟล์ที่แนบมากับความคิดเห็น ไม่ใช่กับตัวฟอร์ม — ว่างคือไฟล์ของคำขอตามปกติ
  comment_id  INTEGER REFERENCES request_comments(id) ON DELETE CASCADE,
  filename    TEXT    NOT NULL,
  stored_name TEXT    NOT NULL,
  mime        TEXT    NOT NULL DEFAULT 'application/octet-stream',
  size        INTEGER NOT NULL DEFAULT 0,
  uploaded_by INTEGER NOT NULL REFERENCES users(id),
  created_at  TEXT    NOT NULL DEFAULT utc_now_text()
);
-- ฐานที่สร้างไว้ก่อนมีคอลัมน์นี้ CREATE TABLE IF NOT EXISTS ข้ามให้เฉย ๆ จึงต้องเติมเอง
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS comment_id INTEGER
  REFERENCES request_comments(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_attach_comment ON attachments(comment_id);

CREATE TABLE IF NOT EXISTS audit_log (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  actor_id   INTEGER REFERENCES users(id),
  action     TEXT    NOT NULL,
  detail     TEXT    NOT NULL DEFAULT '',
  amount     DOUBLE PRECISION,
  created_at TEXT    NOT NULL DEFAULT utc_now_text()
);
CREATE INDEX IF NOT EXISTS idx_audit_req ON audit_log(request_id);

CREATE TABLE IF NOT EXISTS notifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id),
  kind       TEXT    NOT NULL,               -- APPROVAL_REQUEST | CC | RESULT | RETURNED
  channel    TEXT    NOT NULL DEFAULT 'LARK',
  payload    TEXT    NOT NULL DEFAULT '{}',  -- ข้อมูลที่ใช้ประกอบการ์ด
  status     TEXT    NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENT','FAILED','SKIPPED')),
  error      TEXT    NOT NULL DEFAULT '',
  message_id TEXT    NOT NULL DEFAULT '',    -- message_id ที่ Lark คืนมา
  attempts   INTEGER NOT NULL DEFAULT 0,
  created_at TEXT    NOT NULL DEFAULT utc_now_text(),
  sent_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_notif_req    ON notifications(request_id);
CREATE INDEX IF NOT EXISTS idx_notif_status ON notifications(status, id);

CREATE TABLE IF NOT EXISTS delegations (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  to_user    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  from_date  TEXT    NOT NULL,
  to_date    TEXT    NOT NULL,
  reason     TEXT    NOT NULL DEFAULT '',
  active     INTEGER NOT NULL DEFAULT 1,
  created_by INTEGER REFERENCES users(id),
  created_at TEXT    NOT NULL DEFAULT utc_now_text(),
  CHECK (from_user <> to_user)
);
CREATE INDEX IF NOT EXISTS idx_deleg_from ON delegations(from_user, active, from_date, to_date);
CREATE INDEX IF NOT EXISTS idx_deleg_to   ON delegations(to_user, active, from_date, to_date);

CREATE TABLE IF NOT EXISTS issued_documents (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  doc_type   TEXT    NOT NULL CHECK (doc_type IN ('INVOICE','CN','DN','RECEIPT','OTHER')),
  doc_number TEXT    NOT NULL UNIQUE,
  seq        INTEGER NOT NULL,
  period     TEXT    NOT NULL,           -- YYYYMM ที่ใช้เดินเลข
  issued_at  TEXT    NOT NULL DEFAULT utc_now_text(),
  issued_by  INTEGER REFERENCES users(id),
  note       TEXT    NOT NULL DEFAULT '',
  void       INTEGER NOT NULL DEFAULT 0,
  void_reason TEXT   NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_issued_req  ON issued_documents(request_id);
CREATE INDEX IF NOT EXISTS idx_issued_type ON issued_documents(doc_type, period, seq);

CREATE TABLE IF NOT EXISTS sessions (
  id         TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  -- id_token ที่ระบบกลางออกให้ตอนล็อกอิน — ต้องยื่นคืนตอนออกจากระบบ
  -- (ว่าง = ล็อกอินด้วยรหัสผ่านในแอป ไม่ได้ผ่านระบบกลาง)
  id_token   TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT utc_now_text()
);

CREATE TABLE IF NOT EXISTS login_attempts (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT    NOT NULL DEFAULT '',
  ip    TEXT    NOT NULL DEFAULT '',
  ok    INTEGER NOT NULL DEFAULT 0,
  at    TEXT    NOT NULL DEFAULT utc_now_text()
);
CREATE INDEX IF NOT EXISTS idx_login_email ON login_attempts(email, at);
CREATE INDEX IF NOT EXISTS idx_login_ip    ON login_attempts(ip, at);

CREATE TABLE IF NOT EXISTS api_keys (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT    NOT NULL,
  -- แปดตัวแรกของกุญแจ ไว้ให้คนดูออกว่าใบไหนเป็นใบไหนโดยไม่ต้องเก็บตัวจริง
  prefix       TEXT    NOT NULL,
  key_hash     TEXT    NOT NULL UNIQUE,
  -- 0 = อ่านอย่างเดียว · 1 = สร้างคำขอได้ด้วย (อนุมัติผ่าน API ไม่ได้ทุกกรณี)
  can_write    INTEGER NOT NULL DEFAULT 0,
  active       INTEGER NOT NULL DEFAULT 1,
  created_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at   TEXT    NOT NULL DEFAULT utc_now_text(),
  last_used_at TEXT,
  calls        INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_apikey_hash ON api_keys(key_hash, active);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event      TEXT    NOT NULL,
  request_id INTEGER REFERENCES requests(id) ON DELETE SET NULL,
  payload    TEXT    NOT NULL,
  status     TEXT    NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENT','FAILED','SKIPPED')),
  attempts   INTEGER NOT NULL DEFAULT 0,
  http_code  INTEGER NOT NULL DEFAULT 0,
  error      TEXT    NOT NULL DEFAULT '',
  created_at TEXT    NOT NULL DEFAULT utc_now_text(),
  sent_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_hook_status ON webhook_deliveries(status, id);

-- "trigger" เป็นคำสงวนของ Postgres จึงต้องใส่อัญประกาศคู่ทุกที่ที่อ้างถึง
CREATE TABLE IF NOT EXISTS backups (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename    TEXT    NOT NULL,
  size        INTEGER NOT NULL DEFAULT 0,
  files_added INTEGER NOT NULL DEFAULT 0,   -- ไฟล์แนบที่คัดลอกเพิ่มในรอบนี้
  ok          INTEGER NOT NULL DEFAULT 0,
  error       TEXT    NOT NULL DEFAULT '',
  "trigger"   TEXT    NOT NULL DEFAULT 'AUTO' CHECK ("trigger" IN ('AUTO','MANUAL','CRON')),
  duration_ms INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT    NOT NULL DEFAULT utc_now_text()
);
CREATE INDEX IF NOT EXISTS idx_backups_time ON backups(created_at DESC);

-- สถานะฝั่งบัญชี (OneBook) ที่ยิงกลับเข้ามา
--
-- เก็บเป็นประวัติทีละแถว ไม่ใช่คอลัมน์เดียวบนใบคำขอ เพราะเรื่องหนึ่งเดินหลายจังหวะ
-- (รับเรื่อง → ตั้งเจ้าหนี้ → จ่าย) และเวลามีปัญหาต้องตอบได้ว่าแต่ละจังหวะเกิดเมื่อไหร่
--
-- ดัชนีไม่ซ้ำที่ (request_id, state, external_ref) ทำให้ปลายทางยิงซ้ำได้โดยไม่เกิดแถวซ้ำ
-- ซึ่งจำเป็น เพราะระบบที่ยิง webhook ตามปกติจะลองซ้ำเมื่อไม่แน่ใจว่าถึงหรือยัง
CREATE TABLE IF NOT EXISTS external_status (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id   INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
  source       TEXT    NOT NULL DEFAULT '',      -- ชื่อกุญแจ API ที่ยิงเข้ามา
  state        TEXT    NOT NULL CHECK (state IN ('RECEIVED','RECORDED','PAID','REJECTED')),
  external_ref TEXT    NOT NULL DEFAULT '',      -- เลขเอกสารฝั่งบัญชี
  external_url TEXT    NOT NULL DEFAULT '',
  amount       DOUBLE PRECISION,
  occurred_at  TEXT    NOT NULL,
  note         TEXT    NOT NULL DEFAULT '',
  created_at   TEXT    NOT NULL DEFAULT utc_now_text()
);
CREATE INDEX IF NOT EXISTS idx_extstatus_req ON external_status(request_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_extstatus_once
  ON external_status(request_id, state, external_ref);

-- ตัวเดินเลขเอกสาร แยกตามชุดเลขและเดือน
--
-- เดิมเดินเลขด้วย "หาเลขสูงสุดแล้วบวกหนึ่ง" ซึ่งสองคนที่กดพร้อมกันจะอ่านค่าเดียวกัน
-- แล้วได้เลขซ้ำ ชนข้อจำกัด UNIQUE — การใส่ไว้ใน transaction ไม่ได้ช่วย เพราะระดับ
-- การแยกกันเริ่มต้นของ Postgres ยอมให้สองธุรกรรมอ่านค่าเดิมได้พร้อมกัน
--
-- ตารางนี้ทำให้การเดินเลขเป็นการเขียนแถวเดียว ผู้ที่มาทีหลังจะรอแถวนี้แล้วได้เลขถัดไป
CREATE TABLE IF NOT EXISTS doc_counters (
  scope  TEXT    NOT NULL,        -- ชุดเลข เช่น AP-MPRQ หรือ CN
  period TEXT    NOT NULL,        -- YYYYMM
  seq    INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (scope, period)
);

CREATE TABLE IF NOT EXISTS app_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);
